function A = get_A_matrix(%m_i, ... % these are the examples of the possible input
        % ri ... % Only include the inputs that are necessary
        % theta_i ...
        % dtheta_i ...
        % ddtheta_i ...
        % ddr_i, ...
        % I_Gi);

% ENTER YOUR CODE HERE %

A = [ ...
    % 0 0 0 ENTER YOUR MATRIX HERE ; ...
    % ... etc ... ; ..

    ];

end